### ISSUE TITLE
v0.10.3 release plan

### ISSUE THREAD

**Issue by cwhanse** [pvlib/pvlib-python#1928]
We expect to issue v0.10.3 before the end of 2023.

PRs tagged with v0.10.3:

- [x] #1924
- [x] #1907 
- [x] #1905 
- [x] #1875
- [x] #1886 
- [x] #1828 
- [x] #1827 
- [x] #1497
- [x] #1927
- [x] #1930

Issues tagged with v0.10.3

- [x] #1901 will close with #1907
- [x] #1870 
- [x] #1824 will close with #1827

Deferred
- #1883 
- #1904
- #1734 it doesn't look like #1725 will close this, maybe defer @mikofski 
- #1690 would close with #1725
- #1689 no progress since 03/2023
- #1725
- #1893
- [ ] #1856 it looks like #1884 won't be ready for v0.10.3
- [ ] #1922

**Comment by echedey-ls** [comment]
I won't be able to work on #1904 until February; I haven't been around here since college has been and will be tough until then.
Related issues to it (#1734, #1725) are on my personal roadmap; again, when I get back to this.

**Comment by AdamRJensen** [comment]
I had a brief discussion with @kandersolar and made a list of suggested PRs to be deferred (see update to Cliff's list) above.
