### ISSUE TITLE
Glossary page updates tracking

### ISSUE THREAD

**Issue by RDaxini** [pvlib/pvlib-python#2284]
Following on from discussions in #2234 and elsewhere, I thought it would help to create a single separate issue to track and discuss suggested further updates to that page.

- [x] Create page (#2234)
- [ ] Add units
- [ ] "irradiation" -> "irradiance" ([comment](https://github.com/pvlib/pvlib-python/pull/2234#discussion_r1793592373), #2289)
- [x] Adopt [sphinx-hoverxref](https://sphinx-hoverxref.readthedocs.io/en/latest/usage.html#tooltip-on-glossary-terms) ([comment](https://github.com/pvlib/pvlib-python/issues/1421#issuecomment-2403272459), #2290)
- [ ] Enhance definitions (refer to `dni` example)
- [x] Add new definitions (e.g. #2264)
- [ ] Address overlaps and inconsistencies (e.g. #2272)

Supporting: #2234 
Related / additional context: #1421

**Comment by RDaxini** [comment]
@kandersolar could we re-open this? still a few tasks left

**Comment by kandersolar** [comment]
Looks like it was auto-closed by merging @2290.  That's caused by using [magic words](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) like "closes".  If you want to mention an issue but not close it, you have to use vaguer words.  I think "partially addresses" is safe... :P
